### ISSUE TITLE
`resource.yml` templates

### ISSUE THREAD

**Issue by philipsens** [frankframework/charts#18]
It would be nice to have an alias or a template instead of the driver name. This might be something for the framework to implement.

```yaml
jdbc:
  - name: frank2example
    template: postgres
```
